# python of course and we don't need access to sudo atm
language: python

branches:
  only:
  - main

install:
  - pip install pylint
  - pip install nengo
  - pip install multimethod

# run tests
script:
  - pylint ./code/
  - pylint ./color_critter.py
  - python -m pytest --disable-warnings -v
