# python of course and we don't need access to sudo atm
language: python

branches:
  only:
  - main

install:
  - pip install pylint
  - pip install nengo
  - pip install nengo-gui
  - pip install multimethod
  - pip install black

# run tests
script:
  - black ./color_critter_implausible.py
  